name: Build knowledge.json from sitemap

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Build mode"
        required: false
        default: "notes-only"
        type: choice
        options: [notes-only, crawl]
  schedule:
    - cron: "0 7 * * 1"        # every Monday at 07:00 UTC
  push:
    paths: ["scripts/build-knowledge.mjs", "docs/notes.md"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITEMAP_URL: "https://www.destincondogetaways.com/sitemap.xml"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Decide PAGE_LIMIT based on manual input (default notes-only for auto runs)
      - name: Set build mode
        run: |
          MODE="${{ github.event.inputs.mode }}"
          if [ -z "$MODE" ]; then MODE="notes-only"; fi
          if [ "$MODE" = "notes-only" ]; then
            echo "PAGE_LIMIT=0" >> $GITHUB_ENV
            echo "Mode: notes-only (PAGE_LIMIT=0)"
          else
            echo "PAGE_LIMIT=40" >> $GITHUB_ENV
            echo "Mode: crawl (PAGE_LIMIT=40)"
          fi

      # Normalize docs/notes.md so the parser is resilient to copy/paste artifacts
      - name: Normalize docs/notes.md (BOM, NBSP, CRLF)
        if: env.PAGE_LIMIT == '0'
        run: |
          python - <<'PY'
          import pathlib
          p = pathlib.Path('docs/notes.md')
          if p.exists():
              b = p.read_bytes()
              # strip UTF-8 BOM
              if b.startswith(b'\xef\xbb\xbf'):
                  b = b[3:]
              # NBSP -> normal space
              b = b.replace(b'\xc2\xa0', b' ')
              # CRLF/CR -> LF
              b = b.replace(b'\r\n', b'\n').replace(b'\r', b'\n')
              p.write_bytes(b)
          PY

      # Build directly from docs/notes.md when PAGE_LIMIT=0
      - name: Build knowledge.json from notes.md (notes-only)
        if: env.PAGE_LIMIT == '0'
        run: |
          node - <<'NODE'
          const fs = require('fs');

          const mdPath = 'docs/notes.md';
          if (!fs.existsSync(mdPath)) {
            console.error('notes.md not found at', mdPath);
            process.exit(1);
          }

          // Read + in-process normalize as a second safety net
          let text = fs.readFileSync(mdPath, 'utf8');
          if (text.charCodeAt(0) === 0xFEFF) text = text.slice(1);        // BOM
          text = text.replace(/\u00A0/g, ' ');                             // NBSP
          text = text.replace(/\r\n?/g, '\n');                             // CRLF/CR -> LF

          const lines = text.split('\n');

          // Accept optional list bullet before Q: (e.g., "- Q:" or "* Q:" or just "Q:")
          const qRe = /^\s*(?:[-*]\s*)?Q:\s*(.+?)(?:\s*\((.*?)\))?\s*$/i;
          const aRe = /^\s*A:\s*(.+)\s*$/i;

          const faqs = [];

          for (let i = 0; i < lines.length; i++) {
            const qMatch = qRe.exec(lines[i]);
            if (!qMatch) continue;

            const q = (qMatch[1] || '').trim();
            const synRaw = (qMatch[2] || '').trim();
            const tags = synRaw
              ? synRaw.split('/').map(s => s.trim().toLowerCase()).filter(Boolean)
              : [];

            // Find the A: line (skip blank lines)
            let j = i + 1;
            while (j < lines.length && !lines[j].trim()) j++;
            const aMatch = j < lines.length ? aRe.exec(lines[j]) : null;
            if (!aMatch) continue;

            // Collect multi-line answer until blank line or next Q:
            let answer = (aMatch[1] || '').trim();
            let k = j + 1;
            while (k < lines.length) {
              const L = lines[k];
              if (!L.trim()) break;             // blank line ends the answer
              if (qRe.test(L)) break;           // next question begins
              answer += ' ' + L.trim();
              k++;
            }

            faqs.push({ tags, q, a: answer });
            i = k - 1; // advance to the line before the next scan start
          }

          if (!faqs.length) {
            console.error('Parsed 0 FAQs from notes.md — check formatting (Q: … then A: …).');
            process.exit(1);
          }

          const out = {
            propertyName: "Destin Condo Getaways",
            contact: { ownerEmail: "ozan@destincondogetaways.com" },
            basics: {},
            policies: {},
            amenities: {},
            faqs,
            docs: []
          };

          fs.writeFileSync('docs/knowledge.json', JSON.stringify(out, null, 2));
          console.log('Wrote docs/knowledge.json with', faqs.length, 'FAQs from notes.md');
          NODE

      # Crawl mode uses your existing script
      - name: Build knowledge.json from sitemap (crawl)
        if: env.PAGE_LIMIT != '0'
        run: node scripts/build-knowledge.mjs

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- docs/knowledge.json; then
            echo "No changes to docs/knowledge.json"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/knowledge.json
          git commit -m "build: update knowledge from notes (or sitemap)"
          git push
