name: Build knowledge.json from sitemap

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 7 * * 1"   # every Monday at 07:00 UTC
  push:
    paths:
      - "scripts/build-knowledge.js"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build knowledge.json
        env:
          SITEMAP_URL: "https://www.destincondogetaways.com/sitemap.xml"
          PAGE_LIMIT: "40"
        run: |
          node scripts/build-knowledge.js

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/knowledge.json
          git commit -m "build: update knowledge from sitemap" || echo "No changes"
          git push
