name: Build knowledge.json from sitemap

on:
  workflow_dispatch:
    inputs:
      mode:
        description: "Build mode"
        required: false
        default: "notes-only"   # choose when you click Run workflow
        type: choice
        options:
          - notes-only
          - crawl
  schedule:
    - cron: "0 7 * * 1"        # every Monday at 07:00 UTC
  push:
    paths:
      - "scripts/build-knowledge.mjs"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SITEMAP_URL: "https://www.destincondogetaways.com/sitemap.xml"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Decide PAGE_LIMIT based on manual input
      # Default to notes-only for scheduled/push runs
      - name: Set build mode
        run: |
          MODE="${{ github.event.inputs.mode }}"
          if [ -z "$MODE" ]; then MODE="notes-only"; fi
          if [ "$MODE" = "notes-only" ]; then
            echo "PAGE_LIMIT=0" >> $GITHUB_ENV
            echo "Mode: notes-only (PAGE_LIMIT=0)"
          else
            echo "PAGE_LIMIT=40" >> $GITHUB_ENV
            echo "Mode: crawl (PAGE_LIMIT=40)"
          fi

      - name: Build knowledge.json
        run: node scripts/build-knowledge.mjs

      - name: Commit & push if changed
        run: |
          if git diff --quiet -- docs/knowledge.json; then
            echo "No changes to docs/knowledge.json"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/knowledge.json
          git commit -m "build: update knowledge from sitemap"
          git push
